---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: syntara-node-dispatcher
rules:
  - apiGroups: [""]
    resources: [pods]
    verbs: [get, create, delete]
  - apiGroups: [""]
    resources: [pods/portforward]
    verbs: [get, create]
