# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: syntara_node_protocol/node.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'syntara_node_protocol/node.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n syntara_node_protocol/node.proto\x12\x0fsyntara.node.v1\"\x88\x02\n\x0e\x45xecuteRequest\x12\x15\n\rinvocation_id\x18\x01 \x01(\t\x12\x18\n\x10protocol_version\x18\x02 \x01(\r\x12-\n\toperation\x18\x03 \x01(\x0e\x32\x1a.syntara.node.v1.Operation\x12\x13\n\x0binputs_json\x18\x04 \x01(\x0c\x12\x18\n\x10\x63redentials_json\x18\x05 \x01(\x0c\x12\x1d\n\x15workflow_context_json\x18\x06 \x01(\x0c\x12\x15\n\rsettings_json\x18\x07 \x01(\x0c\x12\x17\n\x0ftimeout_seconds\x18\x08 \x01(\r\x12\x18\n\x10max_output_bytes\x18\t \x01(\r\",\n\x08Progress\x12\r\n\x05\x65vent\x18\x01 \x01(\t\x12\x11\n\tdata_json\x18\x02 \x01(\x0c\"\x88\x01\n\x06Result\x12\x13\n\x0boutput_json\x18\x01 \x01(\x0c\x12\x13\n\x0bstatus_code\x18\x02 \x01(\r\x12\x16\n\x0estatus_message\x18\x03 \x01(\t\x12\x15\n\rerror_message\x18\x04 \x01(\t\x12\x12\n\nerror_type\x18\x05 \x01(\t\x12\x11\n\tretryable\x18\x06 \x01(\x08\"\x8a\x01\n\x0e\x45xecutionEvent\x12\x15\n\rinvocation_id\x18\x01 \x01(\t\x12-\n\x08progress\x18\x02 \x01(\x0b\x32\x19.syntara.node.v1.ProgressH\x00\x12)\n\x06result\x18\x03 \x01(\x0b\x32\x17.syntara.node.v1.ResultH\x00\x42\x07\n\x05\x65vent\"&\n\rCancelRequest\x12\x15\n\rinvocation_id\x18\x01 \x01(\t\"\"\n\x0e\x43\x61ncelResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\"\x0f\n\rHealthRequest\"9\n\x0eHealthResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\x12\x18\n\x10protocol_version\x18\x02 \x01(\r*-\n\tOperation\x12\x0b\n\x07\x45XECUTE\x10\x00\x12\x13\n\x0f\x43\x41NCEL_EXTERNAL\x10\x01\x32\xf2\x01\n\x0bNodeService\x12M\n\x07\x45xecute\x12\x1f.syntara.node.v1.ExecuteRequest\x1a\x1f.syntara.node.v1.ExecutionEvent0\x01\x12I\n\x06\x43\x61ncel\x12\x1e.syntara.node.v1.CancelRequest\x1a\x1f.syntara.node.v1.CancelResponse\x12I\n\x06Health\x12\x1e.syntara.node.v1.HealthRequest\x1a\x1f.syntara.node.v1.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'syntara_node_protocol.node_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPERATION']._serialized_start=798
  _globals['_OPERATION']._serialized_end=843
  _globals['_EXECUTEREQUEST']._serialized_start=54
  _globals['_EXECUTEREQUEST']._serialized_end=318
  _globals['_PROGRESS']._serialized_start=320
  _globals['_PROGRESS']._serialized_end=364
  _globals['_RESULT']._serialized_start=367
  _globals['_RESULT']._serialized_end=503
  _globals['_EXECUTIONEVENT']._serialized_start=506
  _globals['_EXECUTIONEVENT']._serialized_end=644
  _globals['_CANCELREQUEST']._serialized_start=646
  _globals['_CANCELREQUEST']._serialized_end=684
  _globals['_CANCELRESPONSE']._serialized_start=686
  _globals['_CANCELRESPONSE']._serialized_end=720
  _globals['_HEALTHREQUEST']._serialized_start=722
  _globals['_HEALTHREQUEST']._serialized_end=737
  _globals['_HEALTHRESPONSE']._serialized_start=739
  _globals['_HEALTHRESPONSE']._serialized_end=796
  _globals['_NODESERVICE']._serialized_start=846
  _globals['_NODESERVICE']._serialized_end=1088
# @@protoc_insertion_point(module_scope)
