"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _Operation:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _OperationEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Operation.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    EXECUTE: _Operation.ValueType  # 0
    CANCEL_EXTERNAL: _Operation.ValueType  # 1
    """Ask an agent adapter to cancel previously acknowledged AO invocations."""

class Operation(_Operation, metaclass=_OperationEnumTypeWrapper): ...

EXECUTE: Operation.ValueType  # 0
CANCEL_EXTERNAL: Operation.ValueType  # 1
"""Ask an agent adapter to cancel previously acknowledged AO invocations."""
Global___Operation: typing_extensions.TypeAlias = Operation

@typing.final
class ExecuteRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INVOCATION_ID_FIELD_NUMBER: builtins.int
    PROTOCOL_VERSION_FIELD_NUMBER: builtins.int
    OPERATION_FIELD_NUMBER: builtins.int
    INPUTS_JSON_FIELD_NUMBER: builtins.int
    CREDENTIALS_JSON_FIELD_NUMBER: builtins.int
    WORKFLOW_CONTEXT_JSON_FIELD_NUMBER: builtins.int
    SETTINGS_JSON_FIELD_NUMBER: builtins.int
    TIMEOUT_SECONDS_FIELD_NUMBER: builtins.int
    MAX_OUTPUT_BYTES_FIELD_NUMBER: builtins.int
    invocation_id: builtins.str
    protocol_version: builtins.int
    operation: Global___Operation.ValueType
    inputs_json: builtins.bytes
    """JSON bytes preserve arbitrary workflow schemas and exact integer values.
    Each field must contain a JSON object. Credentials never appear in metadata.
    """
    credentials_json: builtins.bytes
    workflow_context_json: builtins.bytes
    settings_json: builtins.bytes
    timeout_seconds: builtins.int
    max_output_bytes: builtins.int
    def __init__(
        self,
        *,
        invocation_id: builtins.str = ...,
        protocol_version: builtins.int = ...,
        operation: Global___Operation.ValueType = ...,
        inputs_json: builtins.bytes = ...,
        credentials_json: builtins.bytes = ...,
        workflow_context_json: builtins.bytes = ...,
        settings_json: builtins.bytes = ...,
        timeout_seconds: builtins.int = ...,
        max_output_bytes: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["credentials_json", b"credentials_json", "inputs_json", b"inputs_json", "invocation_id", b"invocation_id", "max_output_bytes", b"max_output_bytes", "operation", b"operation", "protocol_version", b"protocol_version", "settings_json", b"settings_json", "timeout_seconds", b"timeout_seconds", "workflow_context_json", b"workflow_context_json"]) -> None: ...

Global___ExecuteRequest: typing_extensions.TypeAlias = ExecuteRequest

@typing.final
class Progress(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EVENT_FIELD_NUMBER: builtins.int
    DATA_JSON_FIELD_NUMBER: builtins.int
    event: builtins.str
    data_json: builtins.bytes
    def __init__(
        self,
        *,
        event: builtins.str = ...,
        data_json: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["data_json", b"data_json", "event", b"event"]) -> None: ...

Global___Progress: typing_extensions.TypeAlias = Progress

@typing.final
class Result(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OUTPUT_JSON_FIELD_NUMBER: builtins.int
    STATUS_CODE_FIELD_NUMBER: builtins.int
    STATUS_MESSAGE_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    ERROR_TYPE_FIELD_NUMBER: builtins.int
    RETRYABLE_FIELD_NUMBER: builtins.int
    output_json: builtins.bytes
    status_code: builtins.int
    status_message: builtins.str
    error_message: builtins.str
    error_type: builtins.str
    retryable: builtins.bool
    def __init__(
        self,
        *,
        output_json: builtins.bytes = ...,
        status_code: builtins.int = ...,
        status_message: builtins.str = ...,
        error_message: builtins.str = ...,
        error_type: builtins.str = ...,
        retryable: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error_message", b"error_message", "error_type", b"error_type", "output_json", b"output_json", "retryable", b"retryable", "status_code", b"status_code", "status_message", b"status_message"]) -> None: ...

Global___Result: typing_extensions.TypeAlias = Result

@typing.final
class ExecutionEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INVOCATION_ID_FIELD_NUMBER: builtins.int
    PROGRESS_FIELD_NUMBER: builtins.int
    RESULT_FIELD_NUMBER: builtins.int
    invocation_id: builtins.str
    @property
    def progress(self) -> Global___Progress: ...
    @property
    def result(self) -> Global___Result: ...
    def __init__(
        self,
        *,
        invocation_id: builtins.str = ...,
        progress: Global___Progress | None = ...,
        result: Global___Result | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["event", b"event", "progress", b"progress", "result", b"result"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["event", b"event", "invocation_id", b"invocation_id", "progress", b"progress", "result", b"result"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["event", b"event"]) -> typing.Literal["progress", "result"] | None: ...

Global___ExecutionEvent: typing_extensions.TypeAlias = ExecutionEvent

@typing.final
class CancelRequest(google.protobuf.message.Message):
    """Cooperative cancellation keeps Execute open so partial output can be returned.
    A disconnected or expired Execute RPC also cancels the node's running work.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INVOCATION_ID_FIELD_NUMBER: builtins.int
    invocation_id: builtins.str
    def __init__(
        self,
        *,
        invocation_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["invocation_id", b"invocation_id"]) -> None: ...

Global___CancelRequest: typing_extensions.TypeAlias = CancelRequest

@typing.final
class CancelResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCEPTED_FIELD_NUMBER: builtins.int
    accepted: builtins.bool
    def __init__(
        self,
        *,
        accepted: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["accepted", b"accepted"]) -> None: ...

Global___CancelResponse: typing_extensions.TypeAlias = CancelResponse

@typing.final
class HealthRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___HealthRequest: typing_extensions.TypeAlias = HealthRequest

@typing.final
class HealthResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    READY_FIELD_NUMBER: builtins.int
    PROTOCOL_VERSION_FIELD_NUMBER: builtins.int
    ready: builtins.bool
    protocol_version: builtins.int
    def __init__(
        self,
        *,
        ready: builtins.bool = ...,
        protocol_version: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["protocol_version", b"protocol_version", "ready", b"ready"]) -> None: ...

Global___HealthResponse: typing_extensions.TypeAlias = HealthResponse
