"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import collections.abc
import grpc
import grpc.aio
import syntara_node_protocol.node_pb2
import sys
import typing

if sys.version_info >= (3, 13):
    import typing as typing_extensions
else:
    import typing_extensions

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str
_NodeServiceExecuteType = typing_extensions.TypeVar(
    '_NodeServiceExecuteType',
    grpc.UnaryStreamMultiCallable[
        syntara_node_protocol.node_pb2.ExecuteRequest,
        syntara_node_protocol.node_pb2.ExecutionEvent,
    ],
    grpc.aio.UnaryStreamMultiCallable[
        syntara_node_protocol.node_pb2.ExecuteRequest,
        syntara_node_protocol.node_pb2.ExecutionEvent,
    ],
    default=grpc.UnaryStreamMultiCallable[
        syntara_node_protocol.node_pb2.ExecuteRequest,
        syntara_node_protocol.node_pb2.ExecutionEvent,
    ],
)

_NodeServiceCancelType = typing_extensions.TypeVar(
    '_NodeServiceCancelType',
    grpc.UnaryUnaryMultiCallable[
        syntara_node_protocol.node_pb2.CancelRequest,
        syntara_node_protocol.node_pb2.CancelResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        syntara_node_protocol.node_pb2.CancelRequest,
        syntara_node_protocol.node_pb2.CancelResponse,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        syntara_node_protocol.node_pb2.CancelRequest,
        syntara_node_protocol.node_pb2.CancelResponse,
    ],
)

_NodeServiceHealthType = typing_extensions.TypeVar(
    '_NodeServiceHealthType',
    grpc.UnaryUnaryMultiCallable[
        syntara_node_protocol.node_pb2.HealthRequest,
        syntara_node_protocol.node_pb2.HealthResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        syntara_node_protocol.node_pb2.HealthRequest,
        syntara_node_protocol.node_pb2.HealthResponse,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        syntara_node_protocol.node_pb2.HealthRequest,
        syntara_node_protocol.node_pb2.HealthResponse,
    ],
)

class NodeServiceStub(typing.Generic[_NodeServiceExecuteType, _NodeServiceCancelType, _NodeServiceHealthType]):
    """A pod accepts one invocation. Execute is never automatically retried."""

    @typing.overload
    def __init__(self: NodeServiceStub[
        grpc.UnaryStreamMultiCallable[
            syntara_node_protocol.node_pb2.ExecuteRequest,
            syntara_node_protocol.node_pb2.ExecutionEvent,
        ],
        grpc.UnaryUnaryMultiCallable[
            syntara_node_protocol.node_pb2.CancelRequest,
            syntara_node_protocol.node_pb2.CancelResponse,
        ],
        grpc.UnaryUnaryMultiCallable[
            syntara_node_protocol.node_pb2.HealthRequest,
            syntara_node_protocol.node_pb2.HealthResponse,
        ],
    ], channel: grpc.Channel) -> None: ...

    @typing.overload
    def __init__(self: NodeServiceStub[
        grpc.aio.UnaryStreamMultiCallable[
            syntara_node_protocol.node_pb2.ExecuteRequest,
            syntara_node_protocol.node_pb2.ExecutionEvent,
        ],
        grpc.aio.UnaryUnaryMultiCallable[
            syntara_node_protocol.node_pb2.CancelRequest,
            syntara_node_protocol.node_pb2.CancelResponse,
        ],
        grpc.aio.UnaryUnaryMultiCallable[
            syntara_node_protocol.node_pb2.HealthRequest,
            syntara_node_protocol.node_pb2.HealthResponse,
        ],
    ], channel: grpc.aio.Channel) -> None: ...

    Execute: _NodeServiceExecuteType

    Cancel: _NodeServiceCancelType

    Health: _NodeServiceHealthType

NodeServiceAsyncStub: typing_extensions.TypeAlias = NodeServiceStub[
    grpc.aio.UnaryStreamMultiCallable[
        syntara_node_protocol.node_pb2.ExecuteRequest,
        syntara_node_protocol.node_pb2.ExecutionEvent,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        syntara_node_protocol.node_pb2.CancelRequest,
        syntara_node_protocol.node_pb2.CancelResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        syntara_node_protocol.node_pb2.HealthRequest,
        syntara_node_protocol.node_pb2.HealthResponse,
    ],
]

class NodeServiceServicer(metaclass=abc.ABCMeta):
    """A pod accepts one invocation. Execute is never automatically retried."""

    @abc.abstractmethod
    def Execute(
        self,
        request: syntara_node_protocol.node_pb2.ExecuteRequest,
        context: _ServicerContext,
    ) -> typing.Union[collections.abc.Iterator[syntara_node_protocol.node_pb2.ExecutionEvent], collections.abc.AsyncIterator[syntara_node_protocol.node_pb2.ExecutionEvent]]: ...

    @abc.abstractmethod
    def Cancel(
        self,
        request: syntara_node_protocol.node_pb2.CancelRequest,
        context: _ServicerContext,
    ) -> typing.Union[syntara_node_protocol.node_pb2.CancelResponse, collections.abc.Awaitable[syntara_node_protocol.node_pb2.CancelResponse]]: ...

    @abc.abstractmethod
    def Health(
        self,
        request: syntara_node_protocol.node_pb2.HealthRequest,
        context: _ServicerContext,
    ) -> typing.Union[syntara_node_protocol.node_pb2.HealthResponse, collections.abc.Awaitable[syntara_node_protocol.node_pb2.HealthResponse]]: ...

def add_NodeServiceServicer_to_server(servicer: NodeServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
